global:
  evaluation_interval: 15s
  scrape_interval: 15s
rule_files:
- alerting_rules/divergence_alerts.yaml
scrape_configs:
- job_name: divergence-detector
  metrics_path: /metrics
  scrape_interval: 5s
  static_configs:
  - targets:
    - localhost:8003
