global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerting_rules/*.yaml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'strategy-mode-manager'
    static_configs:
      - targets: ['host.docker.internal:8000', 'localhost:8000']
    scrape_interval: 5s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: env
        replacement: testing

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']
