sim:
  seed: 42
  seconds: 30
  init_mid: 2500.0
  tick_size: 0.1
  base_spread_ticks: 2
  base_depth: 30.0
  depth_jitter: 0.6
  levels: 5
  regimes:
    - {name: trend_up,   prob: 0.25, mu:  0.20, sigma: 1.8,  dur_mean_s: 30}
    - {name: trend_down, prob: 0.25, mu: -0.20, sigma: 1.8,  dur_mean_s: 30}
    - {name: mean_rev,   prob: 0.40, mu:  0.00, sigma: 1.2,  dur_mean_s: 45}
    - {name: burst,      prob: 0.10, mu:  0.00, sigma: 4.0,  dur_mean_s: 6}
  rates:
    limit_add:   120
    limit_cancel: 80
    market_sweep: 35
  spoof_ratio: 0.08
  sweep_levels_mean: 1.4
  minute_drift_bps: 0.0
latency:
  upstream_ms: 80
  compute_ms: 15
  decision_ms: 10
  downstream_ms: 80
ofi:
  micro_window_ms: 100
  consecutive_windows: 2
  z_window_seconds: 900
  ofi_long_z: 2.0
  ofi_short_z: -2.0
signals:
  thin_spread_bps_max: 16.0
  use_reclaim: true
  reclaim_lookback_ms: 1500
  reclaim_confirm_ms: 100
costs:
  fee_bps: 2.5
  slip_bps_per_100k: 3.0
  notional_per_trade: 50000
eval:
  horizon_ms: 2000
  stop_ticks: 6
  target_ticks: 9
