# V13 OFI+CVD+AI Trading System - 系统配置
# 版本: v13.0
# 创建日期: 2025-10-19
# 最后更新: 2025-10-19

# ============================================================================
# 系统元信息
# ============================================================================
system:
  name: "OFI_CVD_AI_Trading_System"
  version: "v13.0"
  # 环境: development | testing | production
  # 可通过环境变量 ENV 覆盖
  environment: "development"
  
  # 系统描述
  description: "基于订单流失衡(OFI)和累积成交量差(CVD)的AI增强交易系统"
  
  # 系统作者
  author: "V13 Team"
  
  # 创建时间
  created_at: "2025-10-19"

# ============================================================================
# 数据源配置
# ============================================================================
data_source:
  # 数据提供商
  provider: "binance"
  
  # 默认交易对
  default_symbol: "ETHUSDT"
  
  # 支持的交易对列表
  symbols:
    - "ETHUSDT"
    - "BTCUSDT"
  
  # WebSocket配置
  websocket:
    # 连接超时（秒）
    timeout: 30
    
    # 重连间隔（秒）
    reconnect_interval: 5
    
    # 最大重连次数（0表示无限重连）
    max_reconnect_attempts: 0
    
    # Ping间隔（秒）
    ping_interval: 20

# ============================================================================
# 组件配置
# ============================================================================
components:
  # CVD (Cumulative Volume Delta) 组件
  cvd:
    # 是否启用
    enabled: true
    
    # CVD配置文件路径（相对于config目录）
    config_file: "profiles/analysis.env"
    
    # 实时模式配置文件
    realtime_config_file: "profiles/realtime.env"
    
    # 描述
    description: "累积成交量差计算和Z-score标准化"
  
  # OFI (Order Flow Imbalance) 组件
  ofi:
    # 是否启用
    enabled: true
    
    # OFI配置文件路径
    config_file: "binance_config.yaml"
    
    # 描述
    description: "订单流失衡计算和信号分析"
  
  # AI 组件
  ai:
    # 是否启用（当前阶段未启用）
    enabled: false
    
    # AI模型目录
    models_dir: "models"
    
    # 描述
    description: "机器学习模型训练和预测（Stage3）"
  
  # 交易组件
  trading:
    # 是否启用（当前阶段未启用）
    enabled: false
    
    # 交易配置文件
    config_file: "trading.yaml"
    
    # 描述
    description: "实盘交易执行和风险管理（Stage2）"

# ============================================================================
# 路径配置
# ============================================================================
paths:
  # 数据目录
  data_dir: "data"
  
  # 日志目录
  logs_dir: "logs"
  
  # 报告目录
  reports_dir: "docs/reports"
  
  # AI模型目录
  models_dir: "models"
  
  # 配置目录
  config_dir: "config"
  
  # 归档目录
  archive_dir: "../archive"
  
  # 临时文件目录
  temp_dir: "temp"

# ============================================================================
# 性能配置
# ============================================================================
performance:
  # 队列配置
  queue:
    # 最大队列大小
    max_size: 50000
    
    # 队列满时的行为: block | drop_old | drop_new
    # block: 阻塞等待（分析模式）
    # drop_old: 丢弃旧消息（实时模式）
    # drop_new: 丢弃新消息（不推荐）
    full_behavior: "block"
  
  # 批处理配置
  batch:
    # 批处理大小
    size: 1000
    
    # 批处理超时（毫秒）
    timeout_ms: 200
  
  # 刷新配置
  flush:
    # Watermark缓冲区刷新间隔（毫秒）
    watermark_interval_ms: 200
    
    # 指标刷新间隔（毫秒）
    metrics_interval_ms: 10000
    
    # 数据刷新间隔（毫秒）
    data_interval_ms: 60000
  
  # 打印/日志频率
  logging:
    # 诊断信息打印频率（每N笔交易）
    print_every_trades: 1000
    
    # 进度打印频率（秒）
    progress_interval_seconds: 60

# ============================================================================
# 日志配置
# ============================================================================
logging:
  # 日志级别: DEBUG | INFO | WARNING | ERROR | CRITICAL
  level: "INFO"
  
  # 分模式日志级别（策略模式切换时会动态调整）
  level_by_mode:
    active: "INFO"
    quiet: "INFO"
  
  # 日志格式
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
  # 日期格式
  date_format: "%Y-%m-%d %H:%M:%S"
  
  # 日志文件配置
  file:
    # 是否启用文件日志
    enabled: true
    
    # 日志文件路径（相对于logs_dir）
    filename: "system.log"
    
    # 单个日志文件最大大小（MB）
    max_size_mb: 100
    
    # 日志文件备份数量
    backup_count: 5
  
  # 控制台日志配置
  console:
    # 是否启用控制台日志
    enabled: true
    
    # 控制台日志级别（可以与文件日志级别不同）
    level: "INFO"

# ============================================================================
# 监控配置
# ============================================================================
monitoring:
  # 是否启用监控
  enabled: true
  
  # 监控指标收集间隔（秒）
  interval_seconds: 10
  
  # 指标类型
  metrics:
    # 系统指标
    system:
      - "cpu_usage"
      - "memory_usage"
      - "disk_usage"
    
    # 应用指标
    application:
      - "queue_size"
      - "processing_rate"
      - "latency"
      - "error_rate"
    
    # 业务指标
    business:
      - "trade_count"
      - "cvd_value"
      - "ofi_value"
      - "signal_count"

# ============================================================================
# 数据库配置（未来使用）
# ============================================================================
database:
  # 是否启用数据库
  enabled: false
  
  # 数据库类型: sqlite | postgresql | mysql
  type: "sqlite"
  
  # SQLite配置
  sqlite:
    database: "data/system.db"
  
  # PostgreSQL配置（示例）
  postgresql:
    host: "localhost"
    port: 5432
    database: "ofi_cvd_ai"
    # 用户名和密码应从环境变量读取
    # username: ${DB_USER}
    # password: ${DB_PASSWORD}

# ============================================================================
# 测试配置
# ============================================================================
testing:
  # 测试模式
  mode: "unit"  # unit | integration | e2e
  
  # 测试数据目录
  test_data_dir: "tests/data"
  
  # 测试结果目录
  test_results_dir: "tests/results"
  
  # 是否生成测试覆盖率报告
  coverage: true

# ============================================================================
# 策略模式与差异化配置（数字资产市场）
# ============================================================================
strategy:
  name: "ofi_cvd"
  
  # 模式选择: auto（自动切换）| active（固定活跃）| quiet（固定安静）
  mode: "auto"
  
  # 迟滞与去抖配置
  hysteresis:
    window_secs: 60           # 评估窗口长度（秒）
    min_active_windows: 3     # 连续满足活跃判定的窗口数，才切到 active
    min_quiet_windows: 6      # 连续不满足+非活跃时段的窗口数，才回到 quiet
  
  # 触发器配置
  triggers:
    # 时间表触发器
    schedule:
      enabled: true
      timezone: "Asia/Hong_Kong"      # 香港时区 (HKT, UTC+8)
      wrap_midnight: true              # 支持跨午夜窗口
      calendar: "CRYPTO"               # 交易日历: CRYPTO (24/7) | HK | CN | US
      enabled_weekdays: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]  # 数字资产7x24
      holidays: []                     # 数字资产无节假日
      active_windows:                  # 活跃时段（HKT）
        - "09:00-12:00"                # 亚洲早盘高峰
        - "14:00-17:00"                # 亚洲午后
        - "21:00-02:00"                # 欧美高峰（跨午夜，最重要）
        - "06:00-08:00"                # 美洲夜盘尾盘
    
    # 市场活跃度触发器（针对数字资产市场优化）
    market:
      enabled: true
      window_secs: 60                  # 滑动窗口长度
      min_trades_per_min: 500          # 最小成交笔数/分钟（数字资产高频）
      min_quote_updates_per_sec: 100   # 最小报价更新/秒（订单簿更新频繁）
      max_spread_bps: 5                # 最大点差（基点，流动性好时点差小）
      min_volatility_bps: 10           # 最小波动率（基点，数字资产波动性高）
      min_volume_usd: 1000000          # 最小成交量（美元，确保流动性充足）
      winsorize_percentile: 95         # 尖峰过滤（P95截断）
      use_median: true                 # 使用中位数替代平均值（稳健估计）
  
  # 分模式参数配置
  params:
    # OFI 参数
    ofi:
      active:
        bucket_ms: 50                  # 更短的bucket（数字资产高频）
        depth_levels: 15               # 更深的订单簿深度
        watermark_ms: 200              # 更短的水位线（低延迟）
        freeze_ms: 0
        min_qty: 0
      quiet:
        bucket_ms: 500                 # 更长的bucket（降低噪声）
        depth_levels: 5                # 浅订单簿（避免虚假信号）
        watermark_ms: 2000             # 更长的水位线（等待稳定）
        freeze_ms: 100
        min_qty: 0
    
    # CVD 参数
    cvd:
      active:
        window_ticks: 1000             # 更短的窗口（快速反应）
        ema_span: 30                   # 更短的EMA（捕捉短期趋势）
        denoise_sigma: 1.5             # 较小的去噪（保留信号）
        half_life_trades: 200
        winsor_limit: 8.0
        freeze_min: 50
      quiet:
        window_ticks: 10000            # 更长的窗口（平滑噪声）
        ema_span: 300                  # 更长的EMA（过滤假信号）
        denoise_sigma: 4.0             # 更大的去噪（强过滤）
        half_life_trades: 500
        winsor_limit: 6.0
        freeze_min: 100
    
    # 风控参数
    risk:
      active:
        position_limit: 1.5            # 较大的仓位（高流动性支持）
        order_rate_limit_per_min: 1000 # 更高的下单频率
      quiet:
        position_limit: 0.1            # 极小的仓位（避免冲击）
        order_rate_limit_per_min: 20   # 极低的下单频率
    
    # 性能参数
    performance:
      active:
        flush_metrics_interval_ms: 5000
        print_every: 1000
      quiet:
        flush_metrics_interval_ms: 15000
        print_every: 5000

# ============================================================================
# 特性开关（Feature Flags）
# ============================================================================
features:
  # 是否启用新配置系统（本配置文件）
  use_system_config: false  # 默认false，需要明确启用
  
  # 是否启用详细日志
  verbose_logging: false
  
  # 是否启用性能分析
  profiling: false
  
  # 是否启用实验性功能
  experimental: false
  
  # 策略特性
  strategy:
    dynamic_mode_enabled: true         # 启用动态模式切换
    throttle_in_quiet: true            # 安静期降采样/限速
    sample_ratio_quiet: 0.3            # 安静期采样比例
    dry_run: false                     # 干跑模式（仅打印，不切换参数）
    cli_override_priority: true        # CLI 参数优先级高于文件配置

# ============================================================================
# 通知配置（未来使用）
# ============================================================================
notifications:
  # 是否启用通知
  enabled: false
  
  # 通知方式: email | slack | telegram | webhook
  channels:
    - email
  
  # 邮件配置
  email:
    smtp_server: "smtp.gmail.com"
    smtp_port: 587
    # 凭据应从环境变量读取
    # username: ${EMAIL_USER}
    # password: ${EMAIL_PASSWORD}
    # to_addresses:
    #   - "admin@example.com"

# ============================================================================
# 安全配置
# ============================================================================
security:
  # API密钥加密
  encrypt_api_keys: true
  
  # 敏感数据脱敏
  mask_sensitive_data: true
  
  # 允许的IP地址（空表示允许所有）
  allowed_ips: []
  
  # 速率限制
  rate_limiting:
    enabled: false
    max_requests_per_minute: 100

# ============================================================================
# 备注
# ============================================================================
# 1. 环境变量覆盖：所有配置都可以通过环境变量覆盖
#    格式：SECTION_KEY（大写，用下划线连接）
#    例如：PERFORMANCE_QUEUE_MAX_SIZE=10000
#
# 2. 环境特定配置：通过 config/environments/{ENV}.yaml 覆盖
#    开发环境：ENV=development
#    测试环境：ENV=testing
#    生产环境：ENV=production
#
# 3. 配置优先级：环境变量 > 环境配置 > 系统配置 > 默认值
#
# 4. 敏感信息：API密钥、密码等应通过环境变量设置，不要写入配置文件
#
# 5. 路径：相对路径会自动转换为相对于项目根目录的绝对路径

