# Strategy parameters - v4 激进优化版
data:
  path: examples/sample_data.csv
  tz: UTC

risk:
  max_trade_risk_pct: 0.01       # 1% per trade
  daily_drawdown_stop_pct: 0.08  # 8% stop
  atr_stop_lo: 0.4               # v4 激进: 进一步收紧止损
  atr_stop_hi: 0.8               # v4 激进: 降低止盈目标
  min_tick_sl_mult: 4            # v4 激进: 降低最小tick倍数
  time_exit_seconds_min: 60      # v4 激进: 缩短最小持仓时间
  time_exit_seconds_max: 600     # v4 激进: 缩短最大持仓时间
  slip_bps_budget_frac: 0.35     # v4 激进: 放宽滑点预算
  fee_bps: 1.5                   # v4 激进: 降低手续费假设
  # Time-based take profit levels
  time_tp_enabled: true
  time_tp_vwap_seconds: 180      # v4 激进: 缩短VWAP止盈时间
  time_tp_15r_seconds: 300       # v4 激进: 缩短1.5R止盈时间
  time_tp_15r_multiplier: 1.2    # v4 激进: 降低止盈倍数

features:
  atr_window: 14
  vwap_window_seconds: 1800
  ofi_window_seconds: 2
  ofi_levels: 5
  z_window: 1200

signals:
  momentum:
    ofi_z_min: 0.7               # v4 激进: 进一步降低
    cvd_z_min: 0.4               # v4 激进: 进一步降低
    min_ret: 0.0
    min_signal_strength: 1.0      # v4 激进: 降低信号强度要求
    thin_book_spread_bps_max: 3.0  # v4 激进: 进一步放宽
    adaptive_thresholds: true
    quantile_window: 3600         # v4 激进: 缩短回看窗口
    momentum_quantile_hi: 0.80    # v4 激进: 降低分位数要求
    momentum_quantile_lo: 0.20    # v4 激进: 提高分位数要求
  divergence:
    cvd_z_max: 0.0
    ofi_z_max: 0.0
    reclaim_bars: 1
    divergence_quantile_hi: 0.70  # v4 激进: 降低分位数要求
    divergence_quantile_lo: 0.30  # v4 激进: 提高分位数要求
  entry:
    use_limit_for_divergence: true
  sizing:
    k_ofi: 0.25                   # v4 激进: 进一步提高仓位
    size_max_usd: 100000          # v4 激进: 提高最大仓位

execution:
  ioc: true
  fok: false
  slippage_budget_check: true
  max_slippage_bps: 15.0          # v4 激进: 进一步放宽滑点
  session_window_minutes: 45      # v4 激进: 进一步放宽会话窗
  reject_on_budget_exceeded: true

backtest:
  initial_equity_usd: 100000
  contract_multiplier: 1.0
  seed: 42
