# Strategy parameters - v6 自适应版
# 根据市场条件动态调整的自适应策略
data:
  path: examples/sample_data.csv
  tz: UTC

risk:
  max_trade_risk_pct: 0.01
  daily_drawdown_stop_pct: 0.08
  atr_stop_lo: 0.18              # 自适应止损
  atr_stop_hi: 1.1               # 自适应止盈
  min_tick_sl_mult: 2
  time_exit_seconds_min: 50
  time_exit_seconds_max: 660
  slip_bps_budget_frac: 0.38
  fee_bps: 1.1
  time_tp_enabled: true
  time_tp_vwap_seconds: 105
  time_tp_15r_seconds: 210
  time_tp_15r_multiplier: 1.4

features:
  atr_window: 14
  vwap_window_seconds: 1800
  ofi_window_seconds: 2
  ofi_levels: 5
  z_window: 1200

signals:
  momentum:
    ofi_z_min: 1.5               # 基础阈值
    cvd_z_min: 0.0
    min_ret: 0.0
    min_signal_strength: 1.8     # 自适应信号强度
    price_momentum_threshold: 0.00005
    thin_book_spread_bps_max: 7.0
    adaptive_thresholds: true    # 启用自适应阈值
    quantile_window: 1800
    momentum_quantile_hi: 0.70
    momentum_quantile_lo: 0.30
  divergence:
    cvd_z_max: 0.0
    ofi_z_max: 0.0
    reclaim_bars: 1
    divergence_quantile_hi: 0.60
    divergence_quantile_lo: 0.40
  entry:
    use_limit_for_divergence: true
  sizing:
    k_ofi: 0.32                  # 自适应仓位
    size_max_usd: 125000

execution:
  ioc: true
  fok: false
  slippage_budget_check: false
  max_slippage_bps: 19.0
  session_window_minutes: 60
  reject_on_budget_exceeded: false

backtest:
  initial_equity_usd: 100000
  contract_multiplier: 1.0
  seed: 42
