# Strategy parameters - v6 动量增强版
# 基于价格动量 + OFI确认的增强策略
data:
  path: examples/sample_data.csv
  tz: UTC

risk:
  max_trade_risk_pct: 0.01
  daily_drawdown_stop_pct: 0.08
  atr_stop_lo: 0.2               # 动量策略需要中等止损
  atr_stop_hi: 1.2               # 6:1盈亏比
  min_tick_sl_mult: 2
  time_exit_seconds_min: 60      # 动量需要更长时间
  time_exit_seconds_max: 720     # 最大持仓时间
  slip_bps_budget_frac: 0.35
  fee_bps: 1.2
  time_tp_enabled: true
  time_tp_vwap_seconds: 120
  time_tp_15r_seconds: 240
  time_tp_15r_multiplier: 1.3

features:
  atr_window: 14
  vwap_window_seconds: 1800
  ofi_window_seconds: 2
  ofi_levels: 5
  z_window: 1200

signals:
  momentum:
    ofi_z_min: 1.0               # 动量确认阈值
    cvd_z_min: 0.0
    min_ret: 0.0
    min_signal_strength: 1.5     # 动量信号强度要求
    price_break_threshold: 0.0001  # 0.01%价格突破阈值
    thin_book_spread_bps_max: 6.0
    adaptive_thresholds: false
    quantile_window: 1800
    momentum_quantile_hi: 0.70
    momentum_quantile_lo: 0.30
  divergence:
    cvd_z_max: 0.0
    ofi_z_max: 0.0
    reclaim_bars: 1
    divergence_quantile_hi: 0.60
    divergence_quantile_lo: 0.40
  entry:
    use_limit_for_divergence: true
  sizing:
    k_ofi: 0.30
    size_max_usd: 120000

execution:
  ioc: true
  fok: false
  slippage_budget_check: false
  max_slippage_bps: 18.0
  session_window_minutes: 60
  reject_on_budget_exceeded: false

backtest:
  initial_equity_usd: 100000
  contract_multiplier: 1.0
  seed: 42
