# Strategy parameters - v6 优化版
# 基于v5成功参数，优化盈亏比
data:
  path: examples/sample_data.csv
  tz: UTC

risk:
  max_trade_risk_pct: 0.01
  daily_drawdown_stop_pct: 0.08
  atr_stop_lo: 0.15              # 收紧止损
  atr_stop_hi: 1.0               # 提高止盈 (6.67:1盈亏比)
  min_tick_sl_mult: 2
  time_exit_seconds_min: 30
  time_exit_seconds_max: 300
  slip_bps_budget_frac: 0.5
  fee_bps: 1.0
  time_tp_enabled: true
  time_tp_vwap_seconds: 60
  time_tp_15r_seconds: 120
  time_tp_15r_multiplier: 1.2

features:
  atr_window: 14
  vwap_window_seconds: 1800
  ofi_window_seconds: 2
  ofi_levels: 5
  z_window: 1200

signals:
  momentum:
    ofi_z_min: 1.5               # 保持v5成功阈值
    cvd_z_min: 0.0
    min_ret: 0.0
    min_signal_strength: 0.0     # 不要求信号强度
    thin_book_spread_bps_max: 10.0
    adaptive_thresholds: false
    quantile_window: 1800
    momentum_quantile_hi: 0.70
    momentum_quantile_lo: 0.30
  divergence:
    cvd_z_max: 0.0
    ofi_z_max: 0.0
    reclaim_bars: 1
    divergence_quantile_hi: 0.60
    divergence_quantile_lo: 0.40
  entry:
    use_limit_for_divergence: true
  sizing:
    k_ofi: 0.35
    size_max_usd: 130000

execution:
  ioc: true
  fok: false
  slippage_budget_check: false
  max_slippage_bps: 25.0
  session_window_minutes: 60
  reject_on_budget_exceeded: false

backtest:
  initial_equity_usd: 100000
  contract_multiplier: 1.0
  seed: 42
