# Strategy parameters (vNext - Strong Constraints)
data:
  path: examples/sample_data.csv
  tz: UTC

risk:
  max_trade_risk_pct: 0.01       # 1% per trade
  daily_drawdown_stop_pct: 0.08  # 8% stop
  atr_stop_lo: 1.2               # vNext: 1.2 x ATR
  atr_stop_hi: 1.6               # 1.6 x ATR
  min_tick_sl_mult: 6            # vNext: min tick stop loss multiplier
  time_exit_seconds_min: 120     # 2 minutes
  time_exit_seconds_max: 900     # 15 minutes
  slip_bps_budget_frac: 0.25     # slip <= 1/4 of expected reward
  fee_bps: 2.0                   # 2 bps per notional per fill
  # Time-based take profit levels
  time_tp_enabled: true          # Enable time-based take profit
  time_tp_vwap_seconds: 300      # First TP at VWAP after 5 minutes
  time_tp_15r_seconds: 600       # Second TP at 1.5R after 10 minutes
  time_tp_15r_multiplier: 1.5    # 1.5R multiplier for second TP

features:
  atr_window: 14
  vwap_window_seconds: 1800      # 30 minutes rolling VWAP
  ofi_window_seconds: 2
  ofi_levels: 5                  # Number of levels for multi-level OFI
  z_window: 1200                 # vNext: 20 minutes z-score window

signals:
  momentum:
    ofi_z_min: 2.2               # vNext: higher threshold
    cvd_z_min: 1.6               # vNext: higher threshold
    min_ret: 0.0
    thin_book_spread_bps_max: 1.2  # vNext: tighter spread
    # Adaptive thresholds using quantiles
    adaptive_thresholds: true
    quantile_window: 5400          # vNext: 1.5 hour lookback
    momentum_quantile_hi: 0.85     # vNext: 85th percentile
    momentum_quantile_lo: 0.15     # vNext: 15th percentile
  divergence:
    cvd_z_max: 0.0
    ofi_z_max: 0.0
    # Adaptive thresholds for divergence
    divergence_quantile_hi: 0.75   # vNext: 75th percentile
    divergence_quantile_lo: 0.25   # vNext: 25th percentile
  entry:
    use_limit_for_divergence: true
  sizing:
    k_ofi: 0.08                   # vNext: lower position coefficient
    size_max_usd: 40000           # vNext: lower max position size

execution:
  ioc: true
  fok: false
  slippage_budget_check: true      # Enable slippage budget checking
  max_slippage_bps: 8.0            # vNext: lower max slippage limit
  reject_on_budget_exceeded: true  # Reject orders when budget exceeded

backtest:
  initial_equity_usd: 100000
  contract_multiplier: 1.0
