# Strategy parameters - v6 平衡版
# 基于v5成功参数，适度优化盈亏比
data:
  path: examples/sample_data.csv
  tz: UTC

risk:
  max_trade_risk_pct: 0.01
  daily_drawdown_stop_pct: 0.08
  atr_stop_lo: 0.2               # 从v5的0.2开始，适度收紧
  atr_stop_hi: 0.9               # 4.5:1盈亏比，比v5的1:1更好
  min_tick_sl_mult: 2
  time_exit_seconds_min: 30      # 保持v5的30秒
  time_exit_seconds_max: 300     # 保持v5的300秒
  slip_bps_budget_frac: 0.5      # 保持v5的宽松设置
  fee_bps: 1.0                   # 保持v5的低手续费假设
  time_tp_enabled: true
  time_tp_vwap_seconds: 60       # 保持v5的时间设置
  time_tp_15r_seconds: 120
  time_tp_15r_multiplier: 1.2    # 适度提高止盈倍数

features:
  atr_window: 14
  vwap_window_seconds: 1800
  ofi_window_seconds: 2
  ofi_levels: 5
  z_window: 1200

signals:
  momentum:
    ofi_z_min: 1.5               # 保持v5的成功阈值
    cvd_z_min: 0.0               # 保持v5的不使用CVD
    min_ret: 0.0
    min_signal_strength: 1.0     # 降低信号强度要求，从2.0降到1.0
    price_momentum_threshold: 0.00002  # 降低价格动量要求
    thin_book_spread_bps_max: 10.0   # 保持v5的宽松设置
    adaptive_thresholds: false
    quantile_window: 1800
    momentum_quantile_hi: 0.70
    momentum_quantile_lo: 0.30
  divergence:
    cvd_z_max: 0.0
    ofi_z_max: 0.0
    reclaim_bars: 1
    divergence_quantile_hi: 0.60
    divergence_quantile_lo: 0.40
  entry:
    use_limit_for_divergence: true
  sizing:
    k_ofi: 0.35                   # 保持v5的高仓位设置
    size_max_usd: 130000          # 保持v5的高最大仓位

execution:
  ioc: true
  fok: false
  slippage_budget_check: false    # 保持v5的关闭设置
  max_slippage_bps: 25.0          # 保持v5的宽松设置
  session_window_minutes: 60
  reject_on_budget_exceeded: false

backtest:
  initial_equity_usd: 100000
  contract_multiplier: 1.0
  seed: 42
