# 背离检测模块生产环境SLO告警规则
# 版本: v13.0
# 创建日期: 2025-10-20
# 用途: 生产环境SLO监控和告警

groups:
  - name: divergence_slo_critical
    rules:
      # 1. 背离检测延迟过高 (Critical)
      - alert: DivergenceDetectionLatencyCritical
        expr: histogram_quantile(0.95, rate(divergence_detection_latency_seconds_bucket[5m])) > 0.02
        for: 10m
        labels:
          severity: critical
          component: divergence_detection
          slo: latency
        annotations:
          summary: "背离检测延迟过高 (P95 > 20ms)"
          description: "背离检测模块P95延迟超过20ms，持续10分钟。当前值: {{ $value }}s"
          runbook_url: "https://docs.example.com/runbooks/divergence-latency"
      
      # 2. 系统可用性下降 (Critical)
      - alert: SystemAvailabilityCritical
        expr: (up{job="divergence-detector"} == 0) or (rate(divergence_events_total[5m]) == 0)
        for: 5m
        labels:
          severity: critical
          component: system
          slo: availability
        annotations:
          summary: "系统可用性严重下降"
          description: "背离检测系统不可用或停止生成事件，持续5分钟"
          runbook_url: "https://docs.example.com/runbooks/system-availability"
      
      # 3. 错误率过高 (Critical)
      - alert: ErrorRateCritical
        expr: rate(divergence_errors_total[5m]) / rate(divergence_events_total[5m]) > 0.02
        for: 5m
        labels:
          severity: critical
          component: divergence_detection
          slo: error_rate
        annotations:
          summary: "背离检测错误率过高 (> 2%)"
          description: "背离检测模块错误率超过2%，持续5分钟。当前值: {{ $value | humanizePercentage }}"
          runbook_url: "https://docs.example.com/runbooks/error-rate"
      
      # 4. 指标闭合误差过大 (Critical)
      - alert: MetricsClosureErrorCritical
        expr: abs(rate(divergence_events_total{side="bull"}[1h]) + rate(divergence_events_total{side="bear"}[1h]) - rate(divergence_events_total[1h])) / rate(divergence_events_total[1h]) > 0.15
        for: 10m
        labels:
          severity: critical
          component: metrics
          slo: closure
        annotations:
          summary: "指标闭合误差过大 (> 15%)"
          description: "事件计数闭合性误差超过15%，持续10分钟。当前值: {{ $value | humanizePercentage }}"
          runbook_url: "https://docs.example.com/runbooks/metrics-closure"

  - name: divergence_slo_warning
    rules:
      # 1. 背离检测延迟较高 (Warning)
      - alert: DivergenceDetectionLatencyWarning
        expr: histogram_quantile(0.95, rate(divergence_detection_latency_seconds_bucket[5m])) > 0.01
        for: 5m
        labels:
          severity: warning
          component: divergence_detection
          slo: latency
        annotations:
          summary: "背离检测延迟较高 (P95 > 10ms)"
          description: "背离检测模块P95延迟超过10ms，持续5分钟。当前值: {{ $value }}s"
          runbook_url: "https://docs.example.com/runbooks/divergence-latency"
      
      # 2. 系统负载过高 (Warning)
      - alert: SystemLoadHigh
        expr: rate(process_cpu_seconds_total[5m]) > 0.8
        for: 10m
        labels:
          severity: warning
          component: system
          slo: performance
        annotations:
          summary: "系统CPU负载过高 (> 80%)"
          description: "系统CPU使用率超过80%，持续10分钟。当前值: {{ $value | humanizePercentage }}"
          runbook_url: "https://docs.example.com/runbooks/system-load"
      
      # 3. 内存使用过高 (Warning)
      - alert: MemoryUsageHigh
        expr: process_resident_memory_bytes / (1024*1024*1024) > 1.6
        for: 10m
        labels:
          severity: warning
          component: system
          slo: performance
        annotations:
          summary: "系统内存使用过高 (> 1.6GB)"
          description: "系统内存使用超过1.6GB，持续10分钟。当前值: {{ $value }}GB"
          runbook_url: "https://docs.example.com/runbooks/memory-usage"
      
      # 4. 队列积压过多 (Warning)
      - alert: QueueBacklogHigh
        expr: divergence_queue_size > 1000
        for: 5m
        labels:
          severity: warning
          component: divergence_detection
          slo: performance
        annotations:
          summary: "背离检测队列积压过多 (> 1000)"
          description: "背离检测队列积压超过1000个事件，持续5分钟。当前值: {{ $value }}"
          runbook_url: "https://docs.example.com/runbooks/queue-backlog"

  - name: divergence_business_metrics
    rules:
      # 1. 事件数异常 (Warning)
      - alert: EventRateAbnormal
        expr: rate(divergence_events_total[1h]) < 0.1 or rate(divergence_events_total[1h]) > 2.0
        for: 10m
        labels:
          severity: warning
          component: divergence_detection
          slo: business
        annotations:
          summary: "背离事件率异常"
          description: "背离事件率异常，过低(< 0.1/s)或过高(> 2.0/s)。当前值: {{ $value }}/s"
          runbook_url: "https://docs.example.com/runbooks/event-rate"
      
      # 2. 分数中位数过低 (Warning)
      - alert: ScoreMedianLow
        expr: histogram_quantile(0.5, rate(divergence_score_bucket[1h])) < 40
        for: 15m
        labels:
          severity: warning
          component: divergence_detection
          slo: business
        annotations:
          summary: "背离分数中位数过低 (< 40)"
          description: "背离检测分数中位数过低，持续15分钟。当前值: {{ $value }}"
          runbook_url: "https://docs.example.com/runbooks/score-median"
      
      # 3. 命中率过低 (Warning)
      - alert: HitRateLow
        expr: rate(divergence_hits_total[1h]) / rate(divergence_events_total[1h]) < 0.5
        for: 20m
        labels:
          severity: warning
          component: divergence_detection
          slo: business
        annotations:
          summary: "背离检测命中率过低 (< 50%)"
          description: "背离检测命中率过低，持续20分钟。当前值: {{ $value | humanizePercentage }}"
          runbook_url: "https://docs.example.com/runbooks/hit-rate"

  - name: divergence_infrastructure
    rules:
      # 1. 指标导出器不可用 (Critical)
      - alert: MetricsExporterDown
        expr: up{job="divergence-detector"} == 0
        for: 2m
        labels:
          severity: critical
          component: infrastructure
          slo: availability
        annotations:
          summary: "背离检测指标导出器不可用"
          description: "背离检测指标导出器已停止运行，持续2分钟"
          runbook_url: "https://docs.example.com/runbooks/exporter-down"
      
      # 2. 配置文件加载失败 (Warning)
      - alert: ConfigLoadFailed
        expr: increase(divergence_config_load_errors_total[5m]) > 0
        for: 1m
        labels:
          severity: warning
          component: infrastructure
          slo: reliability
        annotations:
          summary: "背离检测配置文件加载失败"
          description: "背离检测配置文件加载失败，过去5分钟失败次数: {{ $value }}"
          runbook_url: "https://docs.example.com/runbooks/config-load"
      
      # 3. 热更新失败 (Warning)
      - alert: HotUpdateFailed
        expr: increase(divergence_hot_update_errors_total[5m]) > 0
        for: 1m
        labels:
          severity: warning
          component: infrastructure
          slo: reliability
        annotations:
          summary: "背离检测热更新失败"
          description: "背离检测热更新失败，过去5分钟失败次数: {{ $value }}"
          runbook_url: "https://docs.example.com/runbooks/hot-update"

  - name: divergence_data_quality
    rules:
      # 1. 数据源连接异常 (Warning)
      - alert: DataSourceConnectionError
        expr: increase(divergence_data_source_errors_total[5m]) > 5
        for: 5m
        labels:
          severity: warning
          component: data_source
          slo: reliability
        annotations:
          summary: "背离检测数据源连接异常"
          description: "背离检测数据源连接错误过多，过去5分钟错误次数: {{ $value }}"
          runbook_url: "https://docs.example.com/runbooks/data-source"
      
      # 2. 数据质量下降 (Warning)
      - alert: DataQualityDegraded
        expr: rate(divergence_invalid_data_total[1h]) / rate(divergence_data_points_total[1h]) > 0.05
        for: 15m
        labels:
          severity: warning
          component: data_quality
          slo: reliability
        annotations:
          summary: "背离检测数据质量下降"
          description: "背离检测数据质量下降，无效数据比例超过5%。当前值: {{ $value | humanizePercentage }}"
          runbook_url: "https://docs.example.com/runbooks/data-quality"

# 告警规则元数据
metadata:
  version: "v13.0"
  created_at: "2025-10-20T05:20:00Z"
  author: "V13 Team"
  description: "背离检测模块生产环境SLO告警规则"
  tags: ["divergence", "slo", "production", "monitoring"]
  
# 告警规则说明
documentation:
  slo_targets:
    latency_p95_max: "10ms"
    latency_p95_critical: "20ms"
    availability_min: "99.9%"
    error_rate_max: "1%"
    error_rate_critical: "2%"
    metrics_closure_error_max: "10%"
    metrics_closure_error_critical: "15%"
  
  escalation_policy:
    warning: "通知技术团队，30分钟内响应"
    critical: "立即通知技术团队，15分钟内响应，必要时自动回滚"
  
  runbook_links:
    base_url: "https://docs.example.com/runbooks"
    divergence_latency: "/divergence-latency"
    system_availability: "/system-availability"
    error_rate: "/error-rate"
    metrics_closure: "/metrics-closure"
