# 生产环境配置
# 覆盖 system.yaml 中的配置
# 用于实盘交易和生产环境

# 系统配置覆盖
system:
  environment: "production"

# 数据源配置覆盖
data_source:
  # 生产环境使用较长的超时时间
  websocket:
    timeout: 60
    reconnect_interval: 10
    max_reconnect_attempts: 10  # 生产环境限制重连次数

# 性能配置覆盖
performance:
  # 生产环境使用大队列
  queue:
    max_size: 100000
  
  # 生产环境优化刷新频率
  flush:
    watermark_interval_ms: 200
    metrics_interval_ms: 30000
  
  # 减少日志打印频率（提高性能）
  logging:
    print_every_trades: 5000
    progress_interval_seconds: 300

# 日志配置覆盖
logging:
  # 生产环境使用WARNING级别（减少日志量）
  level: "WARNING"
  
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
  file:
    filename: "production.log"
    max_size_mb: 500
    backup_count: 10
  
  console:
    # 生产环境可以关闭控制台日志
    enabled: true
    level: "ERROR"  # 只输出错误信息

# 监控配置覆盖
monitoring:
  # 生产环境必须启用监控
  enabled: true
  interval_seconds: 30

# 特性开关覆盖
features:
  # 生产环境关闭所有调试特性
  verbose_logging: false
  profiling: false
  experimental: false
  
  # 策略特性（生产环境）
  strategy:
    dynamic_mode_enabled: true    # 生产环境启用动态切换
    throttle_in_quiet: true       # 安静期降采样（节省资源）
    sample_ratio_quiet: 0.3       # 30%采样
    dry_run: false                # 生产环境实际应用参数
    cli_override_priority: true   # 保留CLI覆盖能力（应急用）

# 策略模式配置覆盖（生产环境 - 保守设置）
strategy:
  mode: "auto"  # 生产环境使用自动模式
  
  # 生产环境使用标准迟滞参数（稳健）
  hysteresis:
    window_secs: 60              # 标准60秒
    min_active_windows: 3        # 标准3个窗口
    min_quiet_windows: 6         # 标准6个窗口
  
  triggers:
    market:
      # 生产环境使用标准阈值（数字资产市场）
      min_trades_per_min: 500
      min_quote_updates_per_sec: 100
      max_spread_bps: 5
      min_volatility_bps: 10
      min_volume_usd: 1000000

# 日志配置覆盖（策略相关）
logging:
  # 生产环境使用INFO级别（记录关键事件）
  level: "INFO"
  
  # 分模式日志级别
  level_by_mode:
    active: "INFO"
    quiet: "INFO"
  
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
  file:
    filename: "production.log"
    max_size_mb: 500
    backup_count: 10
  
  console:
    # 生产环境只输出错误和模式切换事件
    enabled: true
    level: "WARNING"

# 测试配置覆盖
testing:
  mode: "e2e"
  coverage: false

# 数据库配置覆盖
database:
  # 生产环境可能使用PostgreSQL
  enabled: false
  type: "postgresql"
  # 实际配置从环境变量读取

# 通知配置覆盖
notifications:
  # 生产环境启用通知
  enabled: true
  channels:
    - email
    - slack

# 安全配置覆盖
security:
  encrypt_api_keys: true
  mask_sensitive_data: true
  rate_limiting:
    enabled: true
    max_requests_per_minute: 60

